lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # prywatny klucz do podpisywania
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # publiczny klucz do weryfikacji
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
