services:
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: Europe/Warsaw
        container_name: auth-php
        volumes:
            - ./:/app
            - './docker/php/conf.d:/usr/local/etc/php/conf.d'
            - 'php_composer_data:/root/.composer'
        networks:
            - sandbox-network
        healthcheck:
            test: ["CMD", "php", "-v"]
            interval: 5s
            timeout: 5s
            retries: 5

    auth-www:
        build: ./docker/www
        container_name: auth-www
        ports:
            - 8081:80
        volumes:
            - ./:/app
            - ./docker/www/conf.d:/etc/nginx/conf.d
        networks:
            - sandbox-network
        depends_on:
            php:
                condition: service_healthy

volumes:
    php_composer_data:

networks:
  sandbox-network:
    external: true
    name: sandbox-network