imports:
    - { resource: packages/parameters.yaml }

services:
    App\UI\Http\Controller\:
        resource: "../src/UI/Http/Controller"
        tags: ["controller.service_arguments"]
        autowire: true
        autoconfigure: true
    App\Application\:
        resource: "../src/Application"
        autoconfigure: true
        autowire: true

    App\UI\Http\Controller\AuthController:
        autowire: true
        autoconfigure: true
        tags: ["controller.service_arguments"]
        arguments:
            $apiUserUrl: "%api_user_url%"
            $apiCompanyUrl: "%api_company_url%"